console.log("helloworld");
document.head = document.head || document.getElementsByTagName('head')[0]; // ensures that document.head is defined because code might run in different environment than browser or older browser

function changeFavicon(src) {
    var link = document.createElement('link'), oldLink = document.getElementById('dynamic-favicon');
    link.id = 'dynamic-favicon';
    link.rel = 'shortcut icon';
    link.href = src;
    if (oldLink) {
        document.head.removeChild(oldLink);
    }
    document.head.appendChild(link);
    }
function animate(){
    if(typeof animate.i == 'undefined'){
        animate.i = 0;
    }
    // var image = document.getElementById('favicon-data');
    // var text = image.src;
    // var arr = text.split('+');
    // arr.shift();
    // changeFavicon(arr[animate.i]);
    // console.log(arr[animate.i]);
    // animate.i = animate.i + 1;
    // if(animate.i == arr.length){
    //     animate.i = 0;
    // }

    var text = "R0lGODlhEAAQAPEAAAAAAP/QAP///wAAACH5BAkKAAMAIf8LTkVUU0NBUEUyLjADAQAAACwAAAAAEAAQAAAC59w2MxERM8YYY4wxQgghhBAMwzAMwxAEQRAEQRAEwzAMQxAEQRAEQRAIBAaDQSAQCAQCgUAgEAgEAoNBIBAAAAKBQAAACAQCg0AgEAAAAoFAAAAIBAKBQCAQAAACgUAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEDAQEBAAABAQEBAAABAQEDAwEBAQAAAAEBAAAAAQEBAwMDAQEBAAAAAAAAAQEBAwMDAwMBAQEAAAAAAQEBAwMDAwMDAwEBAQEBAQEBAwMDAwMDAwMDAwEBAQEDAwYMCAAQMKAAAh+QQJCgADACwAAAAAEAAQAAAC59w2MxERM8YYY4wxQgghhBAMwzAMwxAEQRAEQRAEwzAMQxAEQRAEQRAIBAaDQSAQCAAAgUAgAAAEAoNBIBAIAACBQCAAAAQCg0AgEAgAAIFAIAAABAKBQCAQCAQCgUAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAABAQEBAAABAQEDAQEBAQAAAAEBAAAAAQEDAwEBAQEBAAAAAAAAAQEBAwMDAQEBAQEAAAAAAQEBAwMDAwMBAQEBAQEBAQEBAwMDAwMDAwEBAQEBAQEBAwMDAwMDAwMDAwEBAQEDAwYMCAAQMKAAAh+QQJPAADACwAAAAAEAAQAAAC59w2MxERM8YYY4wxQgghhBAMwzAMwxAEQRAEQRAEwzAMQxAEAQAEQRAAAAaDQSAQCAQAgEAgEAAAAoNBIBAIBACAQCAQAAACg0AgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEBAQEBAQEBAQEBAAABAQEBAAABAQEBAQEBAQAAAAEBAAAAAQEDAQEBAQEBAAAAAAAAAQEDAwEBAQEBAQEAAAAAAQEBAwMDAQEBAQEBAQEBAQEBAwMDAwMBAQEBAQEBAQEBAwMDAwMDAwEBAQEBAQEBAwMDAwMDAwMDAwEBAQEDAwYMCAAQMKAAAh+QQJCgADACwAAAAAEAAQAAAC59w2MxERM8YYY4wxQgghhBAMwzAMwxAEQRAEQRAEwzAMQxAEABAEQQAABAaDQSAQCAAAgUAgAAAEAoNBIBAIAACBQCAAAAQCg0AgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEBAQEBAQEBAQEAAAEBAQEAAAEBAQEBAQEBAAAAAQEAAAABAQEDAQEBAQEAAAAAAAABAQEDAwEBAQEBAQAAAAABAQEBAwMDAQEBAQEBAQEBAQEBAwMDAwMBAQEBAQEBAQEBAwMDAwMDAwEBAQEBAQEBAwMDAwMDAwMDAwEBAQEDAwYMCAAQMKAAAh+QQJCgADACwAAAAAEAAQAAAC59w2MxERM8YYY4wxQgghhBAMwzAMwxAEQRAEQRAEwzAMQxAAQBAEAQAIBAaDQSAQAAACgUAAAAgEAoNBIBAAAAKBQAAACAQCg0AgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEBAQEBAQEBAQAAAQEBAQAAAQEBAQEBAQEAAAABAQAAAAEBAQEDAQEBAQAAAAAAAAEBAQEDAwEBAQEBAAAAAAEBAQEBAwMDAQEBAQEBAQEBAQEBAwMDAwMBAQEBAQEBAQEBAwMDAwMDAwEBAQEBAQEBAwMDAwMDAwMDAwEBAQEDAwYMCAAQMKAAAh+QQJCgADACwAAAAAEAAQAAAC59w2MxERM8YYY4wxQgghhBAMwzAMwxAEQRAEQRAEwzAMQwAAQRAEABAIBAaDQSAAAAQCgQAAEAgEAoNBIAAABAKBAAAQCAQCg0AgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEBAQEBAQEBAAABAQEBAAABAQEBAQEBAQAAAAEBAAAAAQEBAQEDAQEBAAAAAAAAAQEBAQEDAwEBAQEAAAAAAQEBAQEBAwMDAQEBAQEBAQEBAQEBAwMDAwMBAQEBAQEBAQEBAwMDAwMDAwEBAQEBAQEBAwMDAwMDAwMDAwEBAQEDAwYMCAAQMKAAAh+QQJRgADACwAAAAAEAAQAAAC59w2MxERM8YYY4wxQgghhBAMwzAMwxAEQRAEQRAEwzAMAwAEQRAAQBAIBAaDQQAACAQCAQAgEAgEAoNBAAAIBAIBACAQCAQCg0AgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEBAQEBAQEAAAEBAQEAAAEBAQEBAQEBAAAAAQEAAAABAQEBAQEDAQEAAAAAAAABAQEBAQEDAwEBAQAAAAABAQEBAQEBAwMDAQEBAQEBAQEBAQEBAwMDAwMBAQEBAQEBAQEBAwMDAwMDAwEBAQEBAQEBAwMDAwMDAwMDAwEBAQEDAwYMCAAQMKAAAh+QQJCgADACwAAAAAEAAQAAAC59w2MxERM8YYY4wxQgghhBAMwzAMwxAEQRAEQRAEwzAMQxAEQRAEQRAIBAaDQSAAAAQCgQAAEAgEAoNBIAAABAKBAAAQCAQCg0AgAAAEAoEAABAIBAKBQCAQCAQCgUAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAQEBAQAAAQEBAQEDAQEAAAABAQAAAAEBAQEDAwEBAQAAAAAAAAEBAQEBAwMDAQEBAAAAAAEBAQEBAwMDAwMBAQEBAQEBAQEBAwMDAwMDAwEBAQEBAQEBAwMDAwMDAwMDAwEBAQEDAwYMCAAQMKAAAh+QQJMgADACwAAAAAEAAQAAAC59w2MxERM8YYY4wxQgghhBAMwzAMwxAEQRAEQRAEwzAMQxAEQRAEQRAIBAaDQSAQCAQCgUAgEAgEAoNBIBAAAAKBQAAACAQCg0AgEAAAAoFAAAAIBAKBQCAQAAACgUAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEDAQEBAAABAQEBAAABAQEDAwEBAQAAAAEBAAAAAQEBAwMDAQEBAAAAAAAAAQEBAwMDAwMBAQEAAAAAAQEBAwMDAwMDAwEBAQEBAQEBAwMDAwMDAwMDAwEBAQEDAwYMCAAQMKAAA7";
    var frames = 4;

    switch(animate.i){
        case 0:
            changeFavicon("data:image/gif;base64,"+text.slice(0, text.length/frames));
            break;
        case 1:
            changeFavicon("data:image/gif;base64,"+text.slice(text.length/frames, 2*text.length/frames));
            break;
        case 2:
            changeFavicon("data:image/gif;base64,"+text.slice(2*text.length/frames, 3*text.length/frames));
            break;
        case 3:
            changeFavicon("data:image/gif;base64,"+text.slice(3*text.length/frames, 4*text.length/frames));
            break;
    }
    animate.i = animate.i + 1;  
    if(animate.i == 4){
        animate.i = 0;
    }

}
setInterval(animate, 500);
